"""Drive tests/gvsoc/ubench: time library primitives / whole kernels on GVSoC, many per run.

    cases = [Case.redmule(256, 256, 256), Case.load2d(256, 256, 768, nact=16), Case.gemm(256, 768, 768, mode="all")]
    rows = run_cases(cases)                      # [{"case": Case, "cycles": int}, ...]

The default case set (``calibration_cases``) measures what cost.py needs: RedMulE tile times
for the tile shapes the SigLIP workload uses, 2-D DMA load / per-row store rates for 1..P
concurrent clusters, barrier cost, and each row op on one and on all clusters.

    python -m softhier_mlir.dse.calibrate --home /app/softhier_dse -o calib.json
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from softhier_mlir.sim import gvsoc

HERE = Path(__file__).resolve().parents[2] / "tests" / "gvsoc" / "ubench"
KINDS = ["barrier", "redmule", "load2d", "store", "layernorm", "softmax", "gelu", "add", "add_bias", "scale", "transpose", "gemm", "summa", "zero"]
UB_RE = re.compile(r"\[ub\] (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) cycles=(\d+)")


@dataclass(frozen=True)
class Case:
    kind: str
    p: tuple = ()

    def c_init(self) -> str:
        p = (tuple(self.p) + (0,) * 8)[:8]
        return f"{{ {KINDS.index(self.kind)}, {{ {', '.join(str(int(v)) for v in p)} }} }}"

    # ---- constructors -------------------------------------------------------------------
    @staticmethod
    def barrier() -> "Case":
        return Case("barrier")

    @staticmethod
    def redmule(tm: int, tn: int, tk: int) -> "Case":
        return Case("redmule", (tm, tn, tk))

    @staticmethod
    def load2d(rows: int, cols: int, ld: int, nact: int = 1) -> "Case":
        return Case("load2d", (rows, cols, ld, nact))

    @staticmethod
    def store(rows: int, cols: int, ld: int, nact: int = 1) -> "Case":
        return Case("store", (rows, cols, ld, nact))

    @staticmethod
    def rowop(kind: str, rows: int, cols: int, mode: str = "one") -> "Case":
        return Case(kind, (rows, cols, 1 if mode == "all" else 0))

    @staticmethod
    def gemm(M: int, N: int, K: int, tm: int = 256, tn: int = 256, tk: int = 256, pipeline: int = 1, mode: str = "all") -> "Case":
        return Case("gemm", (M, N, K, tm, tn, tk, pipeline, 1 if mode == "all" else 0))

    @staticmethod
    def summa(M: int, N: int, K: int, T: int = 256, tk: int = 256, pipeline: int = 1) -> "Case":
        return Case("summa", (M, N, K, T, tk, pipeline))

    @staticmethod
    def zero(nbytes: int) -> "Case":
        return Case("zero", (nbytes,))

    def __str__(self) -> str:
        return f"{self.kind}({','.join(str(v) for v in self.p)})"


def write_cases(cases: list[Case], path: Path = HERE / "cases.h") -> None:
    path.write_text("/* generated by softhier_mlir.dse.calibrate */\n#define UB_CASES \\\n" +
                    ", \\\n".join("    " + c.c_init() for c in cases) + "\n")


def stage_app(cases: list[Case], build_dir: Path) -> Path:
    """Copy the ubench app next to its build dir with its own cases.h, so concurrent runs
    (sweep workers, other agents) never share a source file."""
    app = build_dir.parent / (build_dir.name + "_app")
    app.mkdir(parents=True, exist_ok=True)
    shutil.copy2(HERE / "main.c", app / "main.c")
    rt = HERE.parents[2] / "runtime"
    (app / "CMakeLists.txt").write_text(
        f"set(SOURCES ${{CMAKE_CURRENT_SOURCE_DIR}}/main.c {rt}/sh_ops.c PARENT_SCOPE)\nset(INCLUDE_DIRS {rt} PARENT_SCOPE)\n")
    write_cases(cases, app / "cases.h")
    return app


def run_once(cases: list[Case], arch: gvsoc.Arch | None = None, build_dir: str | Path | None = None,
             timeout: int = 7200) -> list[dict]:
    """Build + run ONE simulation with all `cases`; one row per case (cycles = None on failure)."""
    bdir = Path(build_dir or os.environ.get("SOFTHIER_BUILD_DIR") or
                Path(tempfile.gettempdir()) / f"shbuild_{os.getpid()}").resolve()
    app = stage_app(cases, bdir)
    elf = gvsoc.build_sw(app, arch, build_dir=bdir)
    r = gvsoc.run_sim(elf, timeout=timeout)
    got = {int(m.group(1)): int(m.group(11)) for m in UB_RE.finditer(r["stdout"])}
    rows = [{"case": c, "cycles": got.get(i)} for i, c in enumerate(cases)]
    for row in rows:
        row["ok"] = row["cycles"] is not None
    run_cases.last = r
    return rows


def run_cases(cases: list[Case], arch: gvsoc.Arch | None = None, build_dir: str | Path | None = None,
              timeout: int = 7200, split_on_failure: bool = True, verbose: bool = True) -> list[dict]:
    """run_once, and when the simulation dies (some case SEQUENCES segfault the gvsoc NoC model
    although every case passes alone; a crash loses the whole buffered stdout) bisect the list
    into smaller simulations down to single cases. Failed single cases keep cycles = None."""
    rows = run_once(cases, arch, build_dir, timeout)
    bad = [i for i, r in enumerate(rows) if not r["ok"]]
    if not bad or not split_on_failure or len(cases) == 1:
        if bad and verbose:
            print(f"  [ubench] {len(bad)} case(s) failed (rc={run_cases.last['returncode']}): "
                  + ", ".join(str(cases[i]) for i in bad), file=sys.stderr)
        return rows
    if verbose:
        print(f"  [ubench] run of {len(cases)} cases died (rc={run_cases.last['returncode']}, first missing: "
              f"{cases[bad[0]]}); splitting", file=sys.stderr)
    # keep what the crashed run produced, re-run the rest in halves
    todo = bad
    mid = len(todo) // 2
    for part in (todo[:mid], todo[mid:]):
        if not part:
            continue
        sub = run_cases([cases[i] for i in part], arch, build_dir, timeout, True, verbose)
        for i, r in zip(part, sub):
            rows[i] = r
    return rows


run_cases.last = None


def calibration_cases(P: int = 16) -> list[Case]:
    cs = [Case.barrier(), Case.barrier()]
    for t in [(256, 256, 256), (128, 128, 128), (256, 256, 64), (256, 64, 256), (64, 256, 256), (256, 256, 128),
              (256, 128, 256), (128, 256, 256), (256, 256, 32), (256, 32, 256), (512, 256, 256), (256, 512, 256), (256, 256, 512)]:
        cs.append(Case.redmule(*t))
    for rows, cols in [(256, 256), (256, 64), (64, 256), (256, 128), (128, 128), (256, 32), (32, 256)]:
        cs.append(Case.load2d(rows, cols, 768, 1))
        cs.append(Case.store(rows, cols, 768, 1))
    for n in sorted({2, 3, 4, 6, 8, 12, P} - {1}):
        if n <= P:
            cs.append(Case.load2d(256, 256, 768, n))
    cs.append(Case.store(256, 256, 768, P))   # concurrent stores from a subset of clusters crash gvsoc (2026-10-08)
    cs += [Case.zero(131072), Case.zero(32768), Case.zero(131072)]
    for kind in ["layernorm", "softmax", "gelu", "add", "add_bias", "transpose"]:
        cs.append(Case.rowop(kind, 64, 256, "one"))
        cs.append(Case.rowop(kind, 256, 768, "all"))
    return cs


# ----------------------------------------------------------------------------------------
# fitting CostParams from the calibration rows
# ----------------------------------------------------------------------------------------
def fit(rows: list[dict], arch: "gvsoc.Arch | None" = None, verbose: bool = True):
    """Derive CostParams from calibration rows (as run_cases returns, or loaded from JSON).
    Every timed region includes one global barrier (the first `barrier` case): it is subtracted
    and becomes prm.barrier. Returns (params, report lines)."""
    import numpy as np
    from softhier_mlir.dse import cost
    arch = arch or gvsoc.Arch()
    prm = cost.CostParams()
    rep = []
    get = lambda kind: [(r["case"].p, r["cycles"]) for r in rows if r["case"].kind == kind and r["cycles"] is not None]  # noqa: E731
    bar = [c for _, c in get("barrier")]
    base = min(bar) if bar else 0
    prm.barrier = prm.group_barrier = float(base)
    rep.append(f"barrier (empty timed region): {base} cycles")
    net = lambda c: c - base  # noqa: E731

    # --- DMA load: t = fixed + row*rows + bytes/bw  (bw = link rate; fit fixed + row) ---------
    lb = cost.link_bw(arch)
    ld = [(p, net(c)) for p, c in get("load2d") if p[3] == 1]
    if ld:
        A = np.array([[1.0, p[0]] for p, _ in ld]); y = np.array([c - p[0] * p[1] * 2 / lb for p, c in ld])
        (f0, r0), *_ = np.linalg.lstsq(A, y, rcond=None)
        prm.dma_fixed, prm.dma_row = max(0.0, float(f0)), max(0.0, float(r0))
        rep.append(f"dma load: fixed {prm.dma_fixed:.0f} + {prm.dma_row:.2f}/row + bytes/{lb:.0f}  (n={len(ld)})")
    st = [(p, net(c)) for p, c in get("store") if p[3] == 1 and p[1] * 2 <= 25 * lb]   # issue-bound rows
    if st:
        A = np.array([[1.0, p[0]] for p, _ in st]); y = np.array([float(c) for _, c in st])
        (f0, r0), *_ = np.linalg.lstsq(A, y, rcond=None)
        prm.store_row = max(0.0, float(r0))
        rep.append(f"dma store: fixed {max(0.0, float(f0)):.0f} + max({prm.store_row:.2f}/row, bytes/{lb:.0f})  (n={len(st)})")
    # --- aggregate HBM rate from concurrent loads --------------------------------------------
    multi = [(p, net(c)) for p, c in get("load2d") if p[3] > 1]
    if multi:
        rates = sorted((p[3], p[3] * p[0] * p[1] * 2 / c) for p, c in multi)
        prm.hbm_agg = {1: lb, **{n: r for n, r in rates}}      # measured curve, interpolated by cost.stream_bw
        prm.hbm_bw_scale = rates[-1][1] / (lb * prm.hbm_channels)
        rep.append("aggregate HBM->TCDM: " + ", ".join(f"{n} clusters {r:.1f} B/cyc" for n, r in rates)
                   + " (not monotonic: depends on which mesh rows are active; used as a table)")
    # --- TCDM zero fill through ZOMEM ---------------------------------------------------------
    zr = [(p, net(c)) for p, c in get("zero")]
    if zr:
        big = max(zr, key=lambda t: t[0][0])
        prm.l1_zero_bw = big[0][0] / max(1.0, big[1] - prm.dma_fixed)
        rep.append("zero fill: " + ", ".join(f"{p[0]} B {c} cyc" for p, c in zr) + f" -> {prm.l1_zero_bw:.0f} B/cyc after the fixed cost")
    # --- RedMulE: grid search block cost + fixed ---------------------------------------------
    rm = [(p, net(c)) for p, c in get("redmule")]
    if rm:
        best = None
        for cb_ in np.arange(0.5, 4.01, 0.05):
            for fx in range(0, 1200, 25):
                prm.redmule_block, prm.redmule_fixed = float(cb_), float(fx)
                err = max(abs(cost.redmule_cycles(arch, prm, *p) - c) / c for p, c in rm)
                if best is None or err < best[0]:
                    best = (err, float(cb_), float(fx))
        prm.redmule_block, prm.redmule_fixed = best[1], best[2]
        rep.append(f"redmule: {prm.redmule_block:.2f} cyc/block, fixed {prm.redmule_fixed:.0f}, max err {100 * best[0]:.1f}% over {len(rm)} tiles")
        for p, c in rm:
            m = cost.redmule_cycles(arch, prm, *p)
            rep.append(f"   {p}: sim {c} model {m:.0f} ({100 * (m - c) / c:+.1f}%)  util {p[0] * p[1] * p[2] / arch.macs_per_cycle / c:.2f}")
    # --- scalar row ops: per-element cost from the single-cluster runs -------------------------
    for kind in ("layernorm", "softmax", "gelu", "add", "add_bias", "scale", "transpose"):
        one = [(p, net(c)) for p, c in get(kind) if p[2] == 0]
        if not one:
            continue
        prm.elem[kind] = 1.0
        for p, c in one:
            e = cost.rowop_est(arch, prm, kind, p[0], p[1], False)
            dma = e.cycles - e.compute
            prm.elem[kind] = max(1.0, (c - dma) / (p[0] * p[1]))
        rep.append(f"{kind}: {prm.elem[kind]:.1f} cycles/element (one cluster, {one[-1][0][0]}x{one[-1][0][1]})")
        alls = [(p, net(c)) for p, c in get(kind) if p[2] == 1]
        for p, c in alls:
            m = cost.rowop_est(arch, prm, kind, p[0], p[1], True).cycles
            rep.append(f"   {kind} {p[0]}x{p[1]} all clusters: sim {c} model {m:.0f} ({100 * (m - c) / c:+.1f}%)")
    if verbose:
        print("\n".join(rep))
    return prm, rep


def load_rows(path: str) -> list[dict]:
    return [{"case": Case(d["kind"], tuple(d["p"])), "cycles": d["cycles"], "ok": d["cycles"] is not None}
            for d in json.load(open(path))]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--home", default=os.environ.get("SOFTHIER_HOME"), help="SoftHier checkout (private copy for arch sweeps)")
    ap.add_argument("-o", "--out", help="JSON output of the raw rows")
    ap.add_argument("--cases", nargs="*", help="kind(p0,p1,..) e.g. gemm(256,768,768,256,256,256,1,1); default: calibration set")
    ap.add_argument("--fit", help="write fitted CostParams JSON here")
    ap.add_argument("--from-json", help="skip the simulation, fit from a saved rows JSON")
    a = ap.parse_args()
    if a.home:
        gvsoc.set_home(a.home)
    P = gvsoc.Arch().n_clusters
    if a.from_json:
        rows = load_rows(a.from_json)
    else:
        cases = [Case(s.split("(")[0], tuple(int(v) for v in s[s.index("(") + 1:-1].split(",") if v)) for s in a.cases] if a.cases else calibration_cases(P)
        rows = run_cases(cases)
        if not all(r["ok"] for r in rows):
            print(run_cases.last["stdout"][-2000:], file=sys.stderr)
        for r in rows:
            print(f"{str(r['case']):<40} {r['cycles']}")
        print(f"ROI {run_cases.last['roi_ns']} ns, wall {run_cases.last['wall_s']} s")
        if a.out:
            Path(a.out).write_text(json.dumps([{"kind": r["case"].kind, "p": list(r["case"].p), "cycles": r["cycles"]} for r in rows], indent=1))
    if a.fit:
        from softhier_mlir.dse import cost
        prm, _ = fit(rows)
        cost.params_to_json(prm, a.fit)


if __name__ == "__main__":
    main()
