#!/usr/bin/env python3
"""Write <root>/Makefile: rebuild the three Snitch ISS model libraries (integer core, FP subsystem,
FPU sequencer) from a private copy of the gvsoc ISS sources with exactly the flags / object lists
of the shared build tree (/app/install/softhier/build/core/CMakeFiles/
gen_isa_snitch_{,fp_ss_}rv32imfdva_cpp_*_{optim,debug}.dir and pulp.snitch.sequencer_*.dir).

Layout of <root> (default /app/iss_fast; see docs/SIMULATOR_NOTES.md "Host speed of the Snitch ISS"):
    core/models/cpu/iss/          copy of $SH/core/models/cpu/iss (edited)
    pulp/pulp/snitch/sequencer.cpp copy of $SH/pulp/pulp/snitch/sequencer.cpp (edited)
    gen/isa_snitch_rv32imfdva.{cpp,hpp}        regenerated ISA tables (install/models_fix: nseq fix)
    gen/isa_snitch_fp_ss_rv32imfdva.{cpp,hpp}  $SH/build/core (stock)

    python3 tools/iss_fast/gen_makefile.py [root]
    make -C /app/iss_fast -j10 && make -C /app/iss_fast install OUT=/app/install/softhier/install/models_fast
"""
import sys
from pathlib import Path

SH = "/app/install/softhier"
ROOT = sys.argv[1] if len(sys.argv) > 1 else "/app/iss_fast"
ISS = f"{ROOT}/core/models/cpu/iss"
GEN = f"{ROOT}/gen"
B = f"{ROOT}/build"

INC = (f"-I{GEN} -I{ROOT}/core/models -I{SH}/build/core -I{SH}/core/models -I{SH}/pulp "
       f"-I{SH}/core/engine/include")
COMMON_DEFS = ("-D__GVSOC__ -DCONFIG_GVSOC_ISS_FP_WIDTH=64 -DRISCV=1 -DRISCY -fno-strict-aliasing "
               "-DISS_WORD_32 -DCONFIG_GVSOC_ISS_SNITCH=1 -DCONFIG_GVSOC_ISS_SCOREBOARD=1 "
               "-DCONFIG_GVSOC_ISS_PREFETCHER_SIZE=32 -DCONFIG_GVSOC_ISS_RISCV_EXCEPTIONS=1")
CORE_DEFS = (f"--include isa_snitch_rv32imfdva.hpp {COMMON_DEFS} -DCONFIG_GVSOC_ISS_TIMED=1 "
             "-DPIPELINE_STAGES=1 -DCONFIG_ISS_CORE=snitch")
FPSS_DEFS = f"--include isa_snitch_fp_ss_rv32imfdva.hpp {COMMON_DEFS} -DCONFIG_ISS_CORE=snitch_fp_ss"

# flags.make: optim = -g -O3 -fPIC -fno-stack-protector (C: -O2 -g -DNDEBUG -fPIC -fno-stack-protector)
#             debug = -g -O3 -fPIC with -DVP_MEMCHECK_ACTIVE=1 -DVP_TRACE_ACTIVE=1 (C: -O2 -g -DNDEBUG -fPIC)
VARIANTS = {
    "optim": dict(cxx="-g -O3 -fPIC -fno-stack-protector", c="-O2 -g -DNDEBUG -fPIC -fno-stack-protector",
                  defs="", pulpvp=f"{SH}/build/core/engine/libpulpvp.so", sub=""),
    "debug": dict(cxx="-g -O3 -fPIC", c="-O2 -g -DNDEBUG -fPIC",
                  defs="-DVP_MEMCHECK_ACTIVE=1 -DVP_TRACE_ACTIVE=1",
                  pulpvp=f"{SH}/build/core/engine/libpulpvp-debug.so", sub="debug/"),
}

COMMON_SRCS = ["irq/irq_riscv", "snitch/ssr", "prefetch/prefetch_single_line", "csr", "snitch/decode", "lsu",
               "timing", "insn_cache", "core", "exception", "regfile", "resource", "trace", "syscalls",
               "memcheck", "htif", "mmu", "pmp", "gdbserver", "dbg_unit"]
CORE_SRCS = ["snitch/snitch", "snitch/regfile", "exec/exec_inorder", "snitch/iss"]
FPSS_SRCS = ["snitch/snitch_fp_ss", "snitch_fp_ss/exec_inorder", "snitch_fp_ss/iss"]
WRAPPER = f"{SH}/pulp/pulp/cpu/iss/default_iss_wrapper.cpp"
FLEXFLOAT = f"{ISS}/flexfloat/flexfloat.c"


def iss_sources(gen_cpp, extra):
    return [f"{GEN}/{gen_cpp}", WRAPPER] + [f"{ISS}/src/{s}.cpp" for s in extra + COMMON_SRCS] + [FLEXFLOAT]


TARGETS = {
    # cmake target base name: (sources, extra flags, installed relative path)
    "gen_isa_snitch_rv32imfdva_cpp_60335333": (iss_sources("isa_snitch_rv32imfdva.cpp", CORE_SRCS), CORE_DEFS,
                                               "gen_isa_snitch_rv32imfdva_cpp_60335333.so"),
    "gen_isa_snitch_fp_ss_rv32imfdva_cpp_61161152": (iss_sources("isa_snitch_fp_ss_rv32imfdva.cpp", FPSS_SRCS),
                                                     FPSS_DEFS, "gen_isa_snitch_fp_ss_rv32imfdva_cpp_61161152.so"),
    # the sequencer includes <../../../../isa_snitch_rv32imfdva.hpp> relative to its own include dir
    "pulp.snitch.sequencer": ([f"{ROOT}/pulp/pulp/snitch/sequencer.cpp"],
                              f"-I{GEN}/rel/a/b/c", "pulp/snitch/sequencer.so"),
}


def obj_name(src):
    return src.replace("/app/", "").replace("/", "__") + ".o"


def main():
    Path(f"{GEN}/rel/a/b/c").mkdir(parents=True, exist_ok=True)
    hdrs = sorted(str(p) for p in Path(ROOT).rglob("*.hpp") if "/build/" not in str(p) and "/orig/" not in str(p))
    hdrs += sorted(str(p) for p in Path(ISS).rglob("*.h"))
    out = ["# generated by softhier-mlir tools/iss_fast/gen_makefile.py -- do not edit", f"OUT ?= {ROOT}/out",
           "HDRS = " + " \\\n  ".join(hdrs), ""]
    libs, installs = [], []
    for name, (srcs, defs, rel) in TARGETS.items():
        for var, v in VARIANTS.items():
            tname = f"{name}_{var}"
            exports = f"-D{name.replace('.', '_')}_{var}_EXPORTS"
            objs = [f"{B}/{tname}/{obj_name(s)}" for s in srcs]
            lib = f"{B}/{tname}.so"
            libs.append(lib)
            for s, o in zip(srcs, objs):
                cc = "gcc" if s.endswith(".c") else "g++"
                flags = v["c"] if s.endswith(".c") else v["cxx"]
                out.append(f"{o}: {s} $(HDRS)\n\t@mkdir -p $(dir $@)\n\t{cc} {exports} {v['defs']} {INC} {flags} "
                           f"{defs} -c {s} -o $@\n")
            out.append(f"{lib}: {' '.join(objs)}\n\tg++ -fPIC -g -O3 -shared -o $@ $^ "
                       f"-Wl,-rpath,{SH}/build/core/engine {v['pulpvp']} -lz -lpthread -ldl\n")
            dst = f"$(OUT)/{v['sub']}{rel}"
            installs.append(f"\tmkdir -p $(dir {dst}) && cp {lib} {dst}")
    out.insert(3, "all: " + " ".join(libs) + "\n")
    out.append("install: all\n" + "\n".join(installs) + "\n")
    out.append(".PHONY: all install\n")
    Path(f"{ROOT}/Makefile").write_text("\n".join(out))
    print(f"wrote {ROOT}/Makefile: {len(libs)} libraries, {len(hdrs)} header deps")


if __name__ == "__main__":
    main()
